server:
  port: 8088
spring:
  datasource:
    username: blabla
    password: 123
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: az.itemsharing.userservice.config.CustomOracleDialect
    database: ORACLE
    generate-ddl: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
